### ISSUE TITLE
ThrottlingException

### ISSUE THREAD

**Issue by Gurudatt8** [DNXLabs/terraform-aws-log-exporter#10]
### Contact Details (optional)

gurudatt.suryabhat@rapyder.com

### Description. What happened?

Hi,

I used this updated Lambda code and on testing I see it's throwing me an error: 

{
  "errorMessage": "An error occurred (ThrottlingException) when calling the ListTagsLogGroup operation (reached max retries: 4): Rate exceeded",
  "errorType": "ClientError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 29, in lambda_handler\n    response = logs.list_tags_log_group(logGroupName=log_group['logGroupName'])\n",
    "  File \"/var/runtime/botocore/client.py\", line 386, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/runtime/botocore/client.py\", line 705, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
  ]
}

As mentioned in the code, I have given max_retries = 10

Still I see the throttling error! Can you plz help with this?

### Steps to reproduce

1. Tagged all log groups (150) with ExportToS3=true
2. created lambda function and updated the code with environmental variable s3 bucket name
3. s3 bucket is created and updated the bucket policy
4. also attached the assume role to lambda function

### Actual behavior

Throwing the Throttling error for max_retries=4 

### Occurrence

Frequently

### Relevant log output

```shell
{
  "errorMessage": "An error occurred (ThrottlingException) when calling the ListTagsLogGroup operation (reached max retries: 4): Rate exceeded",
  "errorType": "ClientError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 29, in lambda_handler\n    response = logs.list_tags_log_group(logGroupName=log_group['logGroupName'])\n",
    "  File \"/var/runtime/botocore/client.py\", line 386, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/runtime/botocore/client.py\", line 705, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
  ]
}

Function Logs
START RequestId: 5cd084b8-b887-42bf-8dbf-3980ece48914 Version: $LATEST
--> S3_BUCKET=cloudwatch-retention-group
[ERROR] ClientError: An error occurred (ThrottlingException) when calling the ListTagsLogGroup operation (reached max retries: 4): Rate exceeded
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 29, in lambda_handler
    response = logs.list_tags_log_group(logGroupName=log_group['logGroupName'])
  File "/var/runtime/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)END RequestId: 5cd084b8-b887-42bf-8dbf-3980ece48914
REPORT RequestId: 5cd084b8-b887-42bf-8dbf-3980ece48914	Duration: 13773.75 ms	Billed Duration: 13774 ms	Memory Size: 128 MB	Max Memory Used: 68 MB	Init Duration: 364.40 ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adenot** [comment]
We might need to put a sleep after line 29 to avoid hitting the AWS api in a loop
